In [1]:
##########################################################################################
#                                                                                        #
#  888888b.  8888888 .d88888b.   .d8888b.     .d8888b.   .d8888b.      d8888      d8888  #
#  888  "88b   888  d88P" "Y88b d88P  Y88b   d88P  Y88b d88P  Y88b    d8P888     d8P888  #
#  888  .88P   888  888     888 Y88b.        888        888          d8P 888    d8P 888  #
#  8888888K.   888  888     888  "Y888b.     888d888b.  888d888b.   d8P  888   d8P  888  #
#  888  "Y88b  888  888     888     "Y88b.   888P "Y88b 888P "Y88b d88   888  d88   888  #
#  888    888  888  888     888       "888   888    888 888    888 8888888888 8888888888 #
#  888   d88P  888  Y88b. .d88P Y88b  d88P   Y88b  d88P Y88b  d88P       888        888  #
#  8888888P" 8888888 "Y88888P"   "Y8888P"     "Y8888P"   "Y8888P"        888        888  #
#                                                                                        # 
##########################################################################################
#
# Python Refresher
#
##########################################################################################

In [2]:
##################################################################################################################
#
# YouDo:
#    1) Make a copy of this notebook with your name as a suffix:  
#           M0_Python_Refresher_FirstLast
#    2) Put it in your folder undr students
#    3) Ensure you are in your branch in git 
#    2) Do all work in this new notebook.
#
##################################################################################################################

# Python Refresher

## Basic Data Structures

The most basic "thing" in python is called an "object".  Basically anything you imagine as "data" would be represented by some number of Python objects.   Python provides several "built-in object types", like _integers_ and _strings_, which are useful for storing and manipulating various data.


The following table lists the fundamental Python object types.

| Type Abbreviation  | Type Full Name| Notes |
| ------------- | ------------- |-------------| 
| str | string  | Text |
| int | integer | Decimal-free numbers |
| float | Floating point Number | A decimal number |
| bool | Boolean | Can be either True or False |
| list | List | An indexed, ordered, collection of other types |
| dict| Dictionary | A 1-to-1 lookup table |
| set | Set | As in set-theory.  A collection of unique objects  |


The following cells show how to create objects of different types.

## Strings

In [3]:
# Strings are surrounded by quotes

s1 = 'This is a string'
s2 = "Double-quotes and single-quotes are equivalent"
s3 = '''This kind can span 
        many lines'''

print(s1)
print(s2) 
print(s3)



This is a string
Double-quotes and single-quotes are equivalent
This kind can span 
        many lines


In [4]:
# Adding strings contatenates them together

L1 = 'Luke. '
L2 = 'I am your father.'
print(L1+L2)

LAdd = L1 + L2

print(LAdd)

Luke. I am your father.
Luke. I am your father.


In [5]:
B0 = '99'
B1 = '98'
B2 = ' bottles of beer'
B3 = ' on the wall'
B4 = 'you take one down, pass it around'

print(B0+B2+B3)
print('\t'+B0+B2)           # '\t' is a tab character
print(B4+'\n'+'\t'+B1+B2+B3)# '\n' is a newline character

99 bottles of beer on the wall
	99 bottles of beer
you take one down, pass it around
	98 bottles of beer on the wall


In [6]:
##################################################################################################################
# YouDo
# In a similar pattern to the cell above, make a set of print statements 
# which makes the next verse of that song.
# 
# In case you didn't grow up in North America:
#   https://en.wikipedia.org/wiki/99_Bottles_of_Beer
#
##################################################################################################################
#######################################  BEGIN STUDENT CODE  #####################################################

#Creating the sentence portion of the song outside of the loop so I can call on it within the loop
B2 = ' bottles of beer'
B3 = ' on the wall'
B4 = 'you take one down, pass it around'

#Remembering how to do a loop so I can do 'n-1 bottles of beer on the wall'
count = 99
while (count > 0):
    print(str(count) + B2 + B3)
    print('\t' + str(count) + B2)           # '\t' is a tab character
    count -= 1
    print(B4 + '\n' + '\t' + str(count) + B2 + B3 + "!\n")# '\n' is a newline character
#######################################   END STUDENT CODE   #####################################################



99 bottles of beer on the wall
	99 bottles of beer
you take one down, pass it around
	98 bottles of beer on the wall!

98 bottles of beer on the wall
	98 bottles of beer
you take one down, pass it around
	97 bottles of beer on the wall!

97 bottles of beer on the wall
	97 bottles of beer
you take one down, pass it around
	96 bottles of beer on the wall!

96 bottles of beer on the wall
	96 bottles of beer
you take one down, pass it around
	95 bottles of beer on the wall!

95 bottles of beer on the wall
	95 bottles of beer
you take one down, pass it around
	94 bottles of beer on the wall!

94 bottles of beer on the wall
	94 bottles of beer
you take one down, pass it around
	93 bottles of beer on the wall!

93 bottles of beer on the wall
	93 bottles of beer
you take one down, pass it around
	92 bottles of beer on the wall!

92 bottles of beer on the wall
	92 bottles of beer
you take one down, pass it around
	91 bottles of beer on the wall!

91 bottles of beer on the wall
	91 bottles of be

## Integers

In [7]:
A = 3        # type is inferred by lack of decimal point
B = int(3)   # explicitly typed
C = int('3') # Casting a numeral/string 3, to the integer value of 3

print(A, B, C)

3 3 3


In [8]:
##################################################################################################################
#
# YouDo:
#    1) In the code below, fix the 3rd term so it computes and prints the integer 12 as the answer
#
##################################################################################################################
#######################################  BEGIN STUDENT CODE  #####################################################

two = 2
three = 3

answer = two * three + 2 * three
print(answer)


#######################################   END STUDENT CODE   #####################################################


12


## Floats

In [9]:
# The type() function will tell you what type a data object is

F0 = 3           # Not a float!
print('F0: ', F0, type(F0))

F1 = float(3)    # Cast to a float!
print('F1: ', F1, type(F1))

F2 = 3 + 0.0     # Added to a float
print('F2: ', F2, type(F2))

F3 = 3.         # A dot on the end makes it a float
print('F3: ', F3, type(F3))

F4 = 3.000      # So does adding decimapl places
print('F4: ', F4, type(F4))

F5 = 1e6-999997 # Scientific notation is a float as well
print('F5: ', F5, type(F5))

F6 = float('inf') # infinity is a float
print('F6: ', F6, type(F6))
#print(F6 + 1)

F7 = float('NaN') # not a number (nan) is a float, too
print('F7: ', F7, type(F7))

F0:  3 <class 'int'>
F1:  3.0 <class 'float'>
F2:  3.0 <class 'float'>
F3:  3.0 <class 'float'>
F4:  3.0 <class 'float'>
F5:  3.0 <class 'float'>
F6:  inf <class 'float'>
F7:  nan <class 'float'>


In [10]:
##################################################################################################################
#
# YouDo:
#    1) Fix the code below so it computes and prints 9.0 (a float) as the answer
#       Hint:  I can do it by adding a single character
#
##################################################################################################################
#######################################  BEGIN STUDENT CODE  #####################################################

two = 2
three = 3.

answer = two * three + three
print('My answer is: ', answer, ' of type ', type(answer))




#######################################   END STUDENT CODE   #####################################################


My answer is:  9.0  of type  <class 'float'>


## Booleans

In [11]:
N1 = True   # Equivalent to 1 in some contexts
N2 = False  # Equivalent to 0 in some contexts

print(N1, N2)


True False


In [12]:
print('True AND False = False')
print(N1 & N2) # You can do logic operations on booleans

print('\nTrue OR False = True')
print(N1 | N2) # You can do logic operations on booleans

True AND False = False
False

True OR False = True
True


In [13]:
# If you add bools, they behave like integers
somebools=[True, True, True, False, True]

print(f'The list has {sum(somebools)} True values')
print(f'The list is {sum(somebools)/len(somebools)*100}% True values')

The list has 4 True values
The list is 80.0% True values


## Lists

In [14]:
darf = [True,2,3,4,'five'] # Lists hold stuff

print(darf[2])  # brackets read a value out (counting starts at zero)

# Use .append(newthing) to add a newthing to the list
darf.append("I am new thing")

print(darf)


3
[True, 2, 3, 4, 'five', 'I am new thing']


In [15]:
# You can get a "slice" (subset) of list items with a colon:

print(darf[3:6]) # Get objects 3 and 4 (doens't include the last one)


[4, 'five', 'I am new thing']


In [25]:
##################################################################################################################
#
# YouDo:
#    1) print the slice of worklist which contains all the items which begin with 3 and no other itemts
#       [30, 32, ..., 38]
#
##################################################################################################################

worklist = list(range(0,50,2))
print(f'Original worklist: {worklist}')

#######################################  BEGIN STUDENT CODE  #####################################################

myslice = worklist[15:20]
print(f'Thirties Subset: {myslice}')



#######################################   END STUDENT CODE   #####################################################


Original worklist: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]
Thirties Subset: [30, 32, 34, 36, 38]


# Dictionaries

In [26]:
# Dictionaries are a key-based map of objects.   

dex = dict()
dex['AllMonths']=['January', 'February', 'March']
dex['Jan']='January'
dex['jan']='January'
dex['JAN']='January'
dex['jan.']='January'
dex['Feb']='February'
dex['Mar']='March'
dex

{'AllMonths': ['January', 'February', 'March'],
 'Jan': 'January',
 'jan': 'January',
 'JAN': 'January',
 'jan.': 'January',
 'Feb': 'February',
 'Mar': 'March'}

In [45]:
# You can use them to make a lookup table

print(f'I was not born in Jan')
print(f"I was not born in {dex['Jan']}")
print(f"I was not born in {dex['AllMonths']}")
print("\n")

#Remembering how to access items in a list
print(f"I was not born in {dex['AllMonths'][1]}")

I was not born in Jan
I was not born in January
I was not born in ['January', 'February', 'March']


I was not born in February


In [47]:
##################################################################################################################
#
# YouDo:
#    1) print the slice of worklist which contains all the items which begin with 3 and no other itemts
#       [30, 32, ..., 38]
#
##################################################################################################################

worklist = list(range(0,50,2))
print(f'Original worklist: {worklist}')

#######################################  BEGIN STUDENT CODE  #####################################################

myslice = worklist[15:20]

print(f'Thirties Subset: {myslice}')



#######################################   END STUDENT CODE   #####################################################


Original worklist: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]
Thirties Subset: [30, 32, 34, 36, 38]


In [56]:
## Very Useful Libraries

### Numerical Python (numpy)
import numpy

### Regular Expressions (re)
import re

### Scientific Python (scipy)
import scipy
    #### Statsmodels
    #### Statistics
    #### Signals
    ### Sci-Kit Learn (sklearn
import sklearn

In [55]:
### Pandas
import pandas

In [84]:
##################################################################################################################
#
# YouDo:
#    1) Print the first, "header" row of the data set
#    2) Print lines 37-40 of the actual data
#
##################################################################################################################
#######################################  BEGIN STUDENT CODE  #####################################################
import numpy as np
data_set = r"C:\Users\sviea\Downloads\data_set.csv" #made a fake data set on my pc
lines = np.genfromtxt(data_set, delimiter = ',') #copy-pasted from the volpy.ipynb from work

print("Printing out my made up data set to see if I can figure this stuff out:\n")
print(lines)
print("-------------------")

print("(1) Print the first, \"header\" row of the data set:\n")
# 1) 
print(lines[0]) #Don't know why this isn't printing the letters A, B, C, D
print("-------------------") 

# 2) 
print("2) Print lines 37-40 of the actual data\n")
print(lines[37:41])
#######################################   END STUDENT CODE   #####################################################


Printing out my made up data set to see if I can figure this stuff out:

[[nan nan nan nan]
 [ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]
 [ 4.  4.  4.  4.]
 [ 5.  5.  5.  5.]
 [ 6.  6.  6.  6.]
 [ 7.  7.  7.  7.]
 [ 8.  8.  8.  8.]
 [ 9.  9.  9.  9.]
 [10. 10. 10. 10.]
 [11. 11. 11. 11.]
 [12. 12. 12. 12.]
 [13. 13. 13. 13.]
 [14. 14. 14. 14.]
 [15. 15. 15. 15.]
 [16. 16. 16. 16.]
 [17. 17. 17. 17.]
 [18. 18. 18. 18.]
 [19. 19. 19. 19.]
 [20. 20. 20. 20.]
 [21. 21. 21. 21.]
 [22. 22. 22. 22.]
 [23. 23. 23. 23.]
 [24. 24. 24. 24.]
 [25. 25. 25. 25.]
 [26. 26. 26. 26.]
 [27. 27. 27. 27.]
 [28. 28. 28. 28.]
 [29. 29. 29. 29.]
 [30. 30. 30. 30.]
 [31. 31. 31. 31.]
 [32. 32. 32. 32.]
 [33. 33. 33. 33.]
 [34. 34. 34. 34.]
 [35. 35. 35. 35.]
 [36. 36. 36. 36.]
 [37. 37. 37. 37.]
 [38. 38. 38. 38.]
 [39. 39. 39. 39.]
 [40. 40. 40. 40.]
 [41. 41. 41. 41.]
 [42. 42. 42. 42.]
 [43. 43. 43. 43.]
 [44. 44. 44. 44.]
 [45. 45. 45. 45.]
 [46. 46. 46. 46.]
 [47. 47. 47. 47.]
 [48. 48. 48. 4